#Diese Datei sollte zwingend im Unterordner .github gespeichert sein. Ansonsten fehler
version: 2
updates:
  - package-ecosystem: "pip" #Gibt den Packegae Manager an f체r Java m체sste beispielsweise Mave verwendet werden
    directory: "/Dependabot" #Gibt den Speicherort der Requriements.txt datei an. Je nach Unterodner ein anderer Name.
    schedule:
      interval: "daily" #Gibt das Intervall an wie h채ufig Dependabot Pullrequests machen sollte (weekly, monthly, w채ren auch Optionen
